!=======================================================================
! Generated by  : PSCAD v4.6.3.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4(3), RT_5(3)
      REAL     RT_6, RT_7, RT_8, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, RT_14

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 18
      IPGB      = NPGB
      NPGB      = NPGB + 4
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_6     = STOF(ISTOF + 10)
      RT_7     = STOF(ISTOF + 11)
      RT_8     = STOF(ISTOF + 12)
      RT_9     = STOF(ISTOF + 13)
      RT_10    = STOF(ISTOF + 14)
      RT_11    = STOF(ISTOF + 15)
      RT_12    = STOF(ISTOF + 16)
      RT_13    = STOF(ISTOF + 17)
      RT_14    = STOF(ISTOF + 18)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_4(IT_0) = STOF(ISTOF + 3 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 6 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[const] Real Constant 

      RT_1 = 1.0

! 20:[const] Real Constant 

      RT_2 = 2.0

! 30:[const] Real Constant 

      RT_3 = 3.0

! 40:[datamerge] Merges data signals into an array 
      RT_4(1) = RT_1
      RT_4(2) = RT_2
      RT_4(3) = RT_3

! 50:[COMP7A] Componente com Fortran: A 
!  Gain

      DO n=1,3
      RT_5(n) = RT_4(n) + 1.12
      end DO

! 60:[pgb] Output Channel 'TesteA'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = RT_5(IVD1_1)
      ENDDO

! 70:[const] Real Constant 

      RT_13 = 0.0

! 80:[const] Real Constant 

      RT_12 = 1.0

! 90:[const] Real Constant 

      RT_14 = 60.0

! 100:[const] Real Constant 

      RT_10 = 0.0

! 110:[const] Real Constant 

      RT_9 = 1.0

! 120:[const] Real Constant 

      RT_11 = 60.0

! 130:[modulator] Amplitude/Frequency/Phase Modulator 
! AM/FM/PM MODULATOR
      RT_7 = RT_12 * SIN(STORF(NSTORF) + RT_13*PI_BY180)
      STORF(NSTORF) = STORF(NSTORF) + TWO_PI*RT_14*DELT
      IF (STORF(NSTORF) .GT.  TWO_PI)  STORF(NSTORF) = STORF(NSTORF) - T&
     &WO_PI
      IF (STORF(NSTORF) .LT. -TWO_PI)  STORF(NSTORF) = STORF(NSTORF) + T&
     &WO_PI
      NSTORF = NSTORF+1
!

! 140:[modulator] Amplitude/Frequency/Phase Modulator 
! AM/FM/PM MODULATOR
      RT_8 = RT_9 * COS(STORF(NSTORF) + RT_10*PI_BY180)
      STORF(NSTORF) = STORF(NSTORF) + TWO_PI*RT_11*DELT
      IF (STORF(NSTORF) .GT.  TWO_PI)  STORF(NSTORF) = STORF(NSTORF) - T&
     &WO_PI
      IF (STORF(NSTORF) .LT. -TWO_PI)  STORF(NSTORF) = STORF(NSTORF) + T&
     &WO_PI
      NSTORF = NSTORF+1
!

! 150:[COMP7B] Componente com Fortran: B 
!  Gain


IF (RT_7 > RT_8) THEN
RT_6 = 5.23
ELSE
RT_6 = -2.1
END IF

! 160:[pgb] Output Channel 'TesteB'

      PGB(IPGB+4) = RT_6

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 10) = RT_6
      STOF(ISTOF + 11) = RT_7
      STOF(ISTOF + 12) = RT_8
      STOF(ISTOF + 13) = RT_9
      STOF(ISTOF + 14) = RT_10
      STOF(ISTOF + 15) = RT_11
      STOF(ISTOF + 16) = RT_12
      STOF(ISTOF + 17) = RT_13
      STOF(ISTOF + 18) = RT_14

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 3 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 6 + IT_0) = RT_5(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 4
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_9     = STOF(ISTOF + 13)
      RT_10    = STOF(ISTOF + 14)
      RT_11    = STOF(ISTOF + 15)
      RT_12    = STOF(ISTOF + 16)
      RT_13    = STOF(ISTOF + 17)
      RT_14    = STOF(ISTOF + 18)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[const] Real Constant 

      RT_1 = 1.0

! 20:[const] Real Constant 

      RT_2 = 2.0

! 30:[const] Real Constant 

      RT_3 = 3.0

! 70:[const] Real Constant 

      RT_13 = 0.0

! 80:[const] Real Constant 

      RT_12 = 1.0

! 90:[const] Real Constant 

      RT_14 = 60.0

! 100:[const] Real Constant 

      RT_10 = 0.0

! 110:[const] Real Constant 

      RT_9 = 1.0

! 120:[const] Real Constant 

      RT_11 = 60.0

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 13) = RT_9
      STOF(ISTOF + 14) = RT_10
      STOF(ISTOF + 15) = RT_11
      STOF(ISTOF + 16) = RT_12
      STOF(ISTOF + 17) = RT_13
      STOF(ISTOF + 18) = RT_14


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[const] Real Constant 
      RT_1 = 1.0

! 20:[const] Real Constant 
      RT_2 = 2.0

! 30:[const] Real Constant 
      RT_3 = 3.0

! 40:[datamerge] Merges data signals into an array 

! 50:[COMP7A] Componente com Fortran: A 

! 60:[pgb] Output Channel 'TesteA'

! 70:[const] Real Constant 
      RT_13 = 0.0

! 80:[const] Real Constant 
      RT_12 = 1.0

! 90:[const] Real Constant 
      RT_14 = 60.0

! 100:[const] Real Constant 
      RT_10 = 0.0

! 110:[const] Real Constant 
      RT_9 = 1.0

! 120:[const] Real Constant 
      RT_11 = 60.0

! 130:[modulator] Amplitude/Frequency/Phase Modulator 

! 140:[modulator] Amplitude/Frequency/Phase Modulator 

! 150:[COMP7B] Componente com Fortran: B 

! 160:[pgb] Output Channel 'TesteB'

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[const] Real Constant 
      RT_1 = 1.0

! 20:[const] Real Constant 
      RT_2 = 2.0

! 30:[const] Real Constant 
      RT_3 = 3.0

! 70:[const] Real Constant 
      RT_13 = 0.0

! 80:[const] Real Constant 
      RT_12 = 1.0

! 90:[const] Real Constant 
      RT_14 = 60.0

! 100:[const] Real Constant 
      RT_10 = 0.0

! 110:[const] Real Constant 
      RT_9 = 1.0

! 120:[const] Real Constant 
      RT_11 = 60.0

      RETURN
      END

