!=======================================================================
! Generated by  : PSCAD v4.6.3.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     w, RT_1, RT_2, RT_3, Ia, Ea, Te

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)
      REAL     RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER ICX, IPGB                           ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 7
      IPGB      = NPGB
      NPGB      = NPGB + 4
      ICX       = NCX
      NCX       = NCX + 1
      INODE     = NNODE + 2
      NNODE     = NNODE + 4
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 4
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      w        = STOF(ISTOF + 1)
      RT_1     = STOF(ISTOF + 2)
      RT_2     = STOF(ISTOF + 3)
      RT_3     = STOF(ISTOF + 4)
      Ia       = STOF(ISTOF + 5)
      Ea       = STOF(ISTOF + 6)
      Te       = STOF(ISTOF + 7)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[var] Variable Input Slider 'Tm'
      RT_3 = CX(CXMAP(ICX+1))

! 60:[sumjct] Summing/Differencing Junctions 
      RT_1 = + Te - RT_3

! 70:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_1
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_2 = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -100.0, 100.0, RVD2_2&
     &, RVD2_1)

! 80:[gain] Gain Block 
!  Gain
      w = 0.7267 * RT_2

! 90:[dc_mac_2w] Two winding DC Machine 
      IVD1_1 = NSTORF
      CALL E_DCM2WDG2_EXE(SS, (IBRCH+2), (IBRCH+1),1,w,0.0)
      Te = STORF(IVD1_1+2)
!

! 100:[pgb] Output Channel 'Te'

      PGB(IPGB+3) = Te

! 110:[pgb] Output Channel 'w'

      PGB(IPGB+4) = w

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
! DC source with specified terminal conditions: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS, (IBRCH+3),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = w
      STOF(ISTOF + 2) = RT_1
      STOF(ISTOF + 3) = RT_2
      STOF(ISTOF + 4) = RT_3
      STOF(ISTOF + 5) = Ia
      STOF(ISTOF + 6) = Ea
      STOF(ISTOF + 7) = Te


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1

! Control Signals
      REAL     Ia, Ea

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 4
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 4
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 4
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      Ia       = STOF(ISTOF + 5)
      Ea       = STOF(ISTOF + 6)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[ammeter] Current Meter 'Ia'
      Ia = ( CBR((IBRCH+4), SS))

! 30:[voltmeter] Voltmeter (Line - Line) 'Ea'
      Ea = EMTDC_VVDC(SS, NT_1, 0)

! 40:[pgb] Output Channel 'Ia'

      PGB(IPGB+1) = Ia

! 50:[pgb] Output Channel 'Ea'

      PGB(IPGB+2) = Ea

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 5) = Ia
      STOF(ISTOF + 6) = Ea


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables
      REAL     RVD9_1(9), RVD10_1(10)
      REAL     RVD10_2(10)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 1
      INODE     = NNODE + 2
      NNODE     = NNODE + 4
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 4
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[var] Variable Input Slider 'Tm'

! 60:[sumjct] Summing/Differencing Junctions 

! 70:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 80:[gain] Gain Block 

! 90:[dc_mac_2w] Two winding DC Machine 
      RVD9_1(1)   = 0.002
      RVD9_1(2)   = -0.003
      RVD9_1(3)   = 0.002
      RVD9_1(4)   = 0.0066
      RVD9_1(5)   = 0.0752
      RVD9_1(6)   = -0.056
      RVD9_1(7)   = 0.0264
      RVD9_1(8)   = 0.224
      RVD9_1(9)   = -0.224
      RVD10_1(1)  = 0.0
      RVD10_1(2)  = 0.0
      RVD10_1(3)  = 0.2
      RVD10_1(4)  = 0.3
      RVD10_1(5)  = 0.4
      RVD10_1(6)  = 0.5
      RVD10_1(7)  = 0.6
      RVD10_1(8)  = 0.7
      RVD10_1(9)  = 0.8
      RVD10_1(10) = 0.9
      RVD10_2(1)  = 0.0
      RVD10_2(2)  = 0.0
      RVD10_2(3)  = 0.2
      RVD10_2(4)  = 0.3
      RVD10_2(5)  = 0.4
      RVD10_2(6)  = 0.5
      RVD10_2(7)  = 0.6
      RVD10_2(8)  = 0.7
      RVD10_2(9)  = 0.8
      RVD10_2(10) = 0.9
      CALL COMPONENT_ID(ICALL_NO,235323534)
      CALL E_DCM2WDG2_CFG(SS, (IBRCH+2), (IBRCH+1),0,1,0.1,0.02,0.004,1.&
     &0,0.55,1.65,0.5,0.1,25.0,1.5,RVD9_1,RVD10_1,RVD10_2,0.7267,0.0)

! 100:[pgb] Output Channel 'Te'

! 110:[pgb] Output Channel 'w'

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_1PVSRC_CFG(0,1,6,0.1,60.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 4
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 4
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 40:[pgb] Output Channel 'Ia'

! 50:[pgb] Output Channel 'Ea'

      RETURN
      END

